### ISSUE TITLE
3d plot example not working with v2.12

### ISSUE THREAD

**Issue by lee1043** [CDAT/vcs#263]
[3D plot example from UVCDAT gallery](https://uvcdat.llnl.gov/examples/vcs3D_cubed_sphere_volume.html) is not reproducible with vcs 2.12 version. 

Error message shows as below.

```
/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/vcs/Canvas.py:3803: UserWarning: Unrecognized vcs plot keyword: grid_file, assuming backend (vtk) keyword
  (keyarg, self.backend.type))
CDMS system error: No such file or directory
CDMS I/O error: Opening file /Users/lee1043/Documents/Research/UV-CDAT/examples/3d_plot/vcs3D_cubed_sphere_volume_grid.nc
Traceback (most recent call last):
  File "cubed_sphere.py", line 15, in <module>
    x.plot( v, dv3d, grid_file="vcs3D_cubed_sphere_volume_grid.nc" )
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/vcs/Canvas.py", line 2690, in plot
    a = self.__plot(arglist, keyargs)
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/vcs/Canvas.py", line 4020, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/vcs/VTKPlots.py", line 690, in plot
    returned.update(self.plot3D(data1, data2, tpl, gm, ren, **kargs))
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/vcs/VTKPlots.py", line 791, in plot3D
    **kargs)  # , plot_type = PlotType.List  )
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/DV3D/Application.py", line 72, in gminit
    self.plot.gminit( var1, var2, **args  )
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/DV3D/PointCloudViewer.py", line 1361, in gminit
    self.init( init=init_args, **args )
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/DV3D/PointCloudViewer.py", line 1372, in init
    self.point_cloud_overview.initialize( init_args, lut = lut, maxStageHeight=self.maxStageHeight  )
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/DV3D/DistributedPointCollections.py", line 694, in initialize
    if init_args: self.point_collection.initialize( init_args, **args )
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/DV3D/MultiVarPointCollection.py", line 500, in initialize
    self.gf = cdms2.open( grid_file ) if grid_file else None
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/cdms2/dataset.py", line 358, in openDataset
    return CdmsFile(path, mode, mpiBarrier=CdMpi)
  File "/Users/lee1043/anaconda2/envs/uvcdat-2.12/lib/python2.7/site-packages/cdms2/dataset.py", line 1091, in __init__
    raise CDMSError('Cannot open file %s (%s)' % (path, err))
cdms2.error.CDMSError: Cannot open file /Users/lee1043/Documents/Research/UV-CDAT/examples/3d_plot/vcs3D_cubed_sphere_volume_grid.nc (Variable not found)
```

**Comment by doutriaux1** [comment]
@ThomasMaxwell any chance you could spare a couple of hours on this to point me in the right direction?

**Comment by doutriaux1** [comment]
Seems to work in nightly, @lee1043 can you confirm that a recent version of vcs work.

**Comment by lee1043** [comment]
@doutriaux1 To reproduce it looks like the [example](https://uvcdat.llnl.gov/examples/vcs3D_cubed_sphere_volume.html) is looking for `grid_file` which is `vcs3D_cubed_sphere_volume_grid.nc` but I cannot find where I can get it. Any idea?

**Comment by lee1043** [comment]
@doutriaux1  never mind,,, I found it from the example page. sorry

**Comment by lee1043** [comment]
![cubed_sphere](https://user-images.githubusercontent.com/17091564/36494855-2f2fe0e6-16e8-11e8-85f3-9a78e0977d02.png)

@doutriaux1 it is working although given result plot is not identical to the [example website](https://uvcdat.llnl.gov/examples/vcs3D_cubed_sphere_volume.html). Thanks for following this issue.

**Comment by lee1043** [comment]
Below is appearing messages what I am getting when I run my Python script:
```
/Users/lee1043/anaconda2/envs/uvcdat-nightly-20180221/lib/python2.7/site-packages/vcs/Canvas.py:3910: UserWarning: Unrecognized vcs plot keyword: grid_file, assuming backend (vtk) keyword
  (keyarg, self.backend.type))
 Init PCViewer, nInputPoints = 23328060, n_overview_points = 500000, n_subproc_points = 500000, nCollections = 7, overview skip index = 46, init_args = ['vcs3D_cubed_sphere_volume_grid.nc', 'file:///Users/lee1043/Documents/Research/UV-CDAT/examples/3d_plot_201802/vcs3D_cubed_sphere_volume.nc', None, ['RELHUM'], [None, None, None, None, None], None, None, 'xyz', 1.7]
ERROR: In /Users/doutriaux1/anaconda2/conda-bld/vtk-cdat_1503063062631/work/IO/Image/vtkPNGReader.cxx, line 117
vtkPNGReader (0x7fa683c0bef0): Unable to open file /Users/lee1043/anaconda2/envs/uvcdat-nightly-20180221/share/vcs/uvcdat.png

initCamera: Camera => ((-108.11442471080369, -476.65927617219285, 84.45227482307195), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)) 
```

**Comment by doutriaux1** [comment]
@lee1043 nice catch on the logo missing. I'll fix it right away.

**Comment by lee1043** [comment]
@doutriaux1 Right, logo is missing, and view angle and shape of 3d volume (here more like separated balls, in example more like gridded volume) are also different.

**Comment by doutriaux1** [comment]
yes not sure what happened on the view. Just noticed it's not working properly in py3 though, fixing this at the same time

**Comment by doutriaux1** [comment]
@lee1043 which os did you test this under? I just created a nightly w/o mesa and it hangs with no picture for me.

**Comment by lee1043** [comment]
@doutriaux1 Mac. Created nightly using below commend:
```
conda create -n uvcdat-nightly-20180221 uvcdat -c uvcdat/label/nightly -c conda-forge -c uvcdat
```

**Comment by doutriaux1** [comment]
@lee1043 I have a bad input file I think, I redownloading the 3Gb file.

**Comment by lee1043** [comment]
@doutriaux1 make sure you will need two input files. 3Gb one and much smaller sized one, but nc files.

**Comment by doutriaux1** [comment]
ok I fixed it. But other dv3d issues persists...
