### ISSUE TITLE
vcs/utils.py -- No module named vtkIOFFMPEGPython

### ISSUE THREAD

**Issue by muryanto1** [CDAT/vcs#358]
vcs, vcsaddons, dv3d, thermo, wk testcases failed with "No module named vtkIOFFMPEGPython"
Details:

`=======================================================================
macos_nightly_py2 -- https://circleci.com/gh/CDAT/cdat/5209
=======================================================================
VCS, vcsaddons, dv3d, thermo, wk tests FAILED

/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/unidata/__init__.py:2: UserWarning: unidata package is deprecated please use genutil.udunits instead of unidata.udunits
  warnings.warn("unidata package is deprecated please use genutil.udunits instead of unidata.udunits")
E
======================================================================
ERROR: Failure: ImportError (No module named vtkIOFFMPEGPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/distiller/project/workdir/thermo/tests/test_thermo_no_coredump.py", line 2, in 
    import thermo,vcs,cdms2
  File "/Users/distiller/project/workdir/thermo/lib/thermo.py", line 6, in 
    import vcs
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/vcs/__init__.py", line 102, in 
    from .utils import *  # noqa
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/vcs/utils.py", line 39, in 
    import vtk
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/vtk/__init__.py", line 95, in 
    from .vtkIOFFMPEG import *
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/vtk/vtkIOFFMPEG.py", line 9, in 
    from vtkIOFFMPEGPython import *
ImportError: No module named vtkIOFFMPEGPython

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

=======================================================================
macos_cdat_latest_channel_py2 -- https://circleci.com/gh/CDAT/cdat/5218
=======================================================================
VCS, vcsaddons, dv3d, thermo, wk tests FAILED

Executing nosetests -A not vtk_ui -s tests/test_vcs_verify_set_ext_2_on_default.py in /Users/distiller/project/workdir/vcs
E
======================================================================
ERROR: Failure: ImportError (No module named vtkIOFFMPEGPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/distiller/project/workdir/vcs/tests/test_vcs_taylor_skills.py", line 1, in <module>
    import basetaylortest
  File "/Users/distiller/project/workdir/vcs/tests/basetaylortest.py", line 1, in <module>
    import basevcstest
  File "/Users/distiller/project/workdir/vcs/tests/basevcstest.py", line 5, in <module>
    import vcs
  File "/Users/distiller/project/workdir/vcs/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/Users/distiller/project/workdir/vcs/vcs/utils.py", line 39, in <module>
    import vtk
  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py2/lib/python2.7/site-packages/vtk/__init__.py", line 95, in <module>
    from .vtkIOFFMPEG import *
  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py2/lib/python2.7/site-packages/vtk/vtkIOFFMPEG.py", line 9, in <module>
    from vtkIOFFMPEGPython import *
ImportError: No module named vtkIOFFMPEGPython
----------------------------------------------------------------------
Ran 1 test in 0.001s
FAILED (errors=1)
Executing nosetests -A not vtk_ui -s tests/test_vcs_taylor_stdlabel.py in /Users/distiller/project/workdir/vcs
`

**Comment by muryanto1** [comment]
Closing this...going to open the issue for cdat repo instead.
