### ISSUE TITLE
vcs test_vcs_configurator_resize is failing

### ISSUE THREAD

**Issue by muryanto1** [CDAT/vcs#359]
linux_nightly_py2 -- https://circleci.com/gh/CDAT/cdat/5311

Test file  : tests_png/test_vcs_configurator_resize.png
Source file: uvcdat-testdata/baselines/vcs/test_vcs_configurator_resize.png
Found Baselines:
- uvcdat-testdata/baselines/vcs/test_vcs_configurator_resize.png
Comparing tests_png/test_vcs_configurator_resize.png uvcdat-testdata/baselines/vcs/test_vcs_configurator_resize.png ... ERROR: In /export/doutriaux1/miniconda2/conda-bld/vtk-cdat_1523889366646/work/Imaging/Core/vtkImageDifference.cxx, line 555
vtkImageDifference (0x48755f0): ExecuteInformation: Input are not the same size.
 Input1 is: 0,813,0,302,0,0
 Input2 is: 0,813,0,303,0,0

diff=13.607843, New best!
All baselines failed! Lowest error (13.607843) exceeds threshold (10.000000).
Saving image diff at tests_png/test_vcs_configurator_resize_diff.png
13.607843
/home/circleci/project/workdir/vcs/tests_png/test_vcs_configurator_resize.png
/home/circleci/project/workdir/vcs/tests_png/test_vcs_configurator_resize_diff.png
/home/circleci/project/workdir/vcs/uvcdat-testdata/baselines/vcs/test_vcs_configurator_resize.png
F
======================================================================
FAIL: testConfiguratorResize (test_vcs_configurator_resize.TestVSConfigurator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/workdir/vcs/tests/test_vcs_configurator_resize.py", line 30, in testConfiguratorResize
    self.checkImage(fnm, pngReady=True)
  File "/home/circleci/project/workdir/vcs/tests/basevcstest.py", line 61, in checkImage
    self.assertEqual(ret, 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.694s

FAILED (failures=1)

**Comment by doutriaux1** [comment]
@muryanto1 looks like we just need to update the baseline. Still curious why it suddenly changed...

**Comment by doutriaux1** [comment]
create braqnch both on vcs and uvcdat-testdata with the same name, run the test suite, copy the new baseline generated by the test suite in uvcdat-data repo , rerun test suite until it passes.
commit and push uvcdat-testdata, commit and push vcs branch, test suite will be exectued and run online.
