### ISSUE TITLE
Hard crash on fresh install "No module named 'vtkIOFFMPEGPython'"

### ISSUE THREAD

**Issue by sterlingbaldwin** [CDAT/vcs#374]
On a fresh install using py3, vcs crashes due to the "No module named 'vtkIOFFMPEGPython'" issue.

Command run: ```conda create -n vcs -c conda-forge -c cdat vcs "python>3"```

Here's the output from running 'conda list'
```
# packages in environment at /anaconda2/envs/jupyter-vcdat:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0                 py36_1000    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.0.2                      py_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cdat_info                 8.0.2018.10.30.07.32.gc2e9630          py36_0    cdat/label/nightly
cdms2                     3.1.0.2018.11.06.10.16.g0c25c93  py36hdde6e19_0    cdat/label/nightly
cdtime                    3.1.0.2018.11.01.10.48.gb8c370e  py36hdc02c5d_0    cdat/label/nightly
cdutil                    8.0.2018.09.10.12.55.gfe08f16          py36_0    cdat/label/nightly
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
clapack                   3.2.1                h470a237_1    conda-forge
cloog                     0.18.0                       10    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distarray                 2.12.2                     py_1    conda-forge
dv3d                      8.0.2018.10.25.14.21.g4afbd51            py_0    cdat/label/nightly
entrypoints               0.2.3                 py36_1002    conda-forge
esmf                      7.1.0r               h35eb876_3    conda-forge
esmpy                     7.1.0r                   py36_1    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
ffmpeg                    3.4.1                         0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
future                    0.17.0                py36_1000    conda-forge
g2clib                    1.6.0                         3    conda-forge
gcc                       4.8.5                         8    conda-forge
genutil                   8.0.2018.05.14.11.32.gc0429f3.npy1.13          py36_0    cdat/label/nightly
gmp                       5.1.2                         6    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
idna                      2.7                   py36_1002    conda-forge
intel-openmp              2019.0                      118    anaconda
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.1.1           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                     <pip>
isl                       0.12.2                        1    conda-forge
jasper                    1.900.1              hff1ad4c_5    conda-forge
jedi                      0.13.1                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
lapack                    3.6.1                         1    conda-forge
libcdms                   3.0.2018.06.12.15.57.ga415a0b               0    cdat/label/nightly
libcf                     3.0.2018.06.27.19.10.g994aa30  py36h1de35cc_0    cdat/label/nightly
libcurl                   7.62.0               hbdb9355_0    conda-forge
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libdrs                    3.0.2018.06.12.16.54.gb71c348               0    cdat/label/nightly
libdrs_f                  3.0.2018.06.26.17.06.gb964d89               0    cdat/label/nightly
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    4.8.5                         1    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libnetcdf                 4.6.1               h350cafa_11    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
mkl                       2017.0.4             h1fae6ae_0    anaconda
mpc                       1.1.0                         5    conda-forge
mpfr                      4.0.1                         0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                h26a2512_5    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf-fortran            4.4.4               h71ea97b_10    conda-forge
nodejs                    10.8.0               hfc679d8_1    conda-forge
notebook                  5.7.0                 py36_1000    conda-forge
numpy                     1.13.1                   py36_0    anaconda
openssl                   1.0.2p               h470a237_1    conda-forge
ossuuid                   1.6.2                hfc679d8_0    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       18.1                  py36_1000    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
prometheus_client         0.4.2                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyrsistent                0.14.5           py36h470a237_1    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.0                py36_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.5.0                   py36_0    conda-forge
sidecar                   0.2.0                     <pip>
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
udunits2                  2.2.27.6             h3a4f0e9_1    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
vcs                       8.0                      py36_0    cdat
vtk-cdat                  8.0.1.8.0                py36_3    cdat/label/nightly
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
widgetsnbextension        3.4.2                     <pip>
x264                      1!152.20180717       h470a237_1    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge```

**Comment by sterlingbaldwin** [comment]
After running ```conda install -c conda-forge "ffmpeg>4"``` I get

```
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/baldwin32/projects/vcs/vcs/__init__.py", line 108, in <module>
    from . import Canvas  # noqa
  File "/Users/baldwin32/projects/vcs/vcs/Canvas.py", line 38, in <module>
    from .VTKPlots import VTKVCSBackend
  File "/Users/baldwin32/projects/vcs/vcs/VTKPlots.py", line 5, in <module>
    from . import vcs2vtk
  File "/Users/baldwin32/projects/vcs/vcs/vcs2vtk.py", line 19, in <module>
    f = open(os.path.join(vcs.vcs_egg_path, "wmo_symbols.json"))
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda2/envs/jupyter-vcdat/lib/python3.6/site-packages/share/vcs/wmo_symbols.json'
```

**Comment by doutriaux1** [comment]
Sterling.

Looks like your are running from the vcs source directory (egg based now)

Try to either run outside of it or create the symlinks so it finds the pcakge
on my mac I had to so:
cd Share
ln -s . vcs

C.

**Comment by doutriaux1** [comment]
@sterlingbaldwin you're on a mac, right?

**Comment by doutriaux1** [comment]
An you're running from the vcs source directory

2 things

1. The install line should be: `conda create -n cdat8 -c cdat/label/v80 -c conda-forge -c cdat python=2.7 vcs python=3`
2. If running from source directory on mac I had to do 
```
cd Share
ln -s . vcs
```

**Comment by zshaheen** [comment]
@doutriaux1 I'm getting this same error. It was fine on macOS, but when using both the Python 2 and Python 3 versions of cdat, I get the `ImportError: No module named vtkIOFFMPEGPython` error.

Any advice?

**Comment by doutriaux1** [comment]
I think you need to force ffmpeg to be >=4

**Comment by doutriaux1** [comment]
Did you try: `conda create -n cdat8 -c cdat/label/v80 -c conda-forge -c cdat python=2.7 cdat`

C.

**Comment by zshaheen** [comment]
Thanks @doutriaux1, the command you suggested worked.  Strangely enough, just installing vcs and cdms still gave that error, but installing cdat completely worked fine.

**Comment by zshaheen** [comment]
Yes, that's the confusing part. Same command as the above, except I had `cdms2 vcs` instead of `cdat`.
