### ISSUE TITLE
Error while importing cdms2  (CDAT)

### ISSUE THREAD

**Issue by JiveshDixit** [CDAT/vcs#456]
`` python3 -c "import cdms2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/uvcdat/2.4.0/lib/python2.7/site-packages/cdms2/__init__.py", line 4, in <module>
    import cdat_info
  File "/usr/local/uvcdat/2.4.0/lib/python2.7/site-packages/cdat_info.py", line 93
    except Exception,err:
                    ^

**Comment by jypeter** [comment]
Are you trying to use python3 to import a very old (pre-conda) python version of cdms2 ? There is no reason this should work!

You have to install a new version: https://github.com/CDAT/cdat/wiki/install

**Comment by JiveshDixit** [comment]
Thank you jypeter.
